### PR TITLE
Add new locations for searching libraries

### PR DESCRIPTION
**Pull request by subins2000**
* Add new locations for searching libraries. This is due to Flatpak packaging
* Use a new environment variable `VARNAM_SUGGESTIONS_DIR` for mentioning the path to `suggestions` folder

### CODE REVIEW

**Comment by navaneeth** [comment]
Couple of questions:

* So how does this work? Who will set this env variable? \
* Can't you get the same behavior by setting XDG_DATA_HOME? 
* Who is responsible for creating this directory on the target system?

**Comment by subins2000** [comment]
* It'll be set in a [wrapper script](https://github.com/subins2000/varnam-flatpak/blob/master/varnam-wrapper.sh)
* `XDG_DATA_HOME` is not varnam specific and used by other programs
* This usecase would be specific to flatpak sandbox. You can see in the wrapper script above how the files from the flatpak sandbox is copied to user's directory.

There was a very compelling reason why I made this new env variable and not use `XDG_DATA_HOME` (I think that didn't work). But I don't remember it now.

**Comment by subins2000** [comment]
Would love to get this merged. I've now initiated to package it officially to Flathub. It currently uses my fork with this change, but better if it's from the original libvarnam

**Comment by subins2000** [comment]
To overcome the fixed paths of **symbols folder** and **suggestions folder**, I've added these 2 new environment variables :

```
VARNAM_SYMBOLS_DIR
VARNAM_SUGGESTIONS_DIR
```

Note that, `symbolsFileSearchPath` variable in `varnam.c` doesn't have a Windows system related folder in it.

**Pull request closed without merging**
